
#ifndef __GEN14MMIO_H__
#define __GEN14MMIO_H__

#include "..\\CommonMMIO.h"
#include "Gen14CommonInterruptRegisters.h"

#define DDI_AUX_CTL_A_GEN14 0x64010
#define DDI_AUX_CTL_B_GEN14 0x64110
#define DDI_AUX_CTL_TC1_GEN14 0x16F210
#define DDI_AUX_CTL_TC2_GEN14 0x16F410
#define DDI_AUX_CTL_TC3_GEN14 0x16F610
#define DDI_AUX_CTL_TC4_GEN14 0x16F810

#define DDI_AUX_DATA_A_START_GEN14 0x64014 // 64014h - 64027h
#define DDI_AUX_DATA_A_END_GEN14 0x64024

#define DDI_AUX_DATA_B_START_GEN14 0x64114 // 64114h - 64127h
#define DDI_AUX_DATA_B_END_GEN14 0x64124

#define DDI_AUX_DATA_TC1_START_GEN14 0x16F214 // 64314h - 64327h
#define DDI_AUX_DATA_TC1_END_GEN14 0x16F224

#define DDI_AUX_DATA_TC2_START_GEN14 0x16F414 // 64414h - 64427h
#define DDI_AUX_DATA_TC2_END_GEN14 0x16F424

#define DDI_AUX_DATA_TC3_START_GEN14 0x16F614 // 64514h - 64527h
#define DDI_AUX_DATA_TC3_END_GEN14 0x16F624

#define DDI_AUX_DATA_TC4_START_GEN14 0x16F814 // 64614h - 64627h
#define DDI_AUX_DATA_TC4_END_GEN14 0x16F824

BOOLEAN GEN14_CMN_MMIOHANDLERS_MasterInterruptCtlMMIOReadHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, PULONG pulReadData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_MasterInterruptCtlMMIOWriteHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, ULONG ulWriteData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_DisplayInterruptCtlMMIOReadHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, PULONG pulReadData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_DisplayInterruptCtlMMIOWriteHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, ULONG ulWriteData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_HotPlugIIRMMIOWriteHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, ULONG ulWriteData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_PICAMMIOWriteHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, ULONG ulWriteData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_DEHotPlugIIRMMIOWriteHandler(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, ULONG ulWriteData, PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_GetLanesAssignedfromphyMMIOReadHandlers(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, PULONG pulReadData,
                                                                        PREGRW_EXEC_SITE peRegRWExecSite);
BOOLEAN GEN14_CMN_MMIOHANDLERS_GetPhyassignedfromphyMMIOReadHandlers(PMMIO_HANDLER_INFO pstMMIOHandlerInfo, ULONG ulMMIOOffset, PULONG pulReadData,
                                                                     PREGRW_EXEC_SITE peRegRWExecSite);
#endif // !__GEN14MMIO_H__
