///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Intel.VPG.Display.Automation
{
    /// <summary>
    /// The class representing the ColorEnhancementNew element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.2")]
    [RepositoryFolder("7304a53c-6fde-4827-8ad0-8f3e0ffaf05d")]
    public partial class ColorEnhancementNew : RepoGenBaseFolder
    {
        static ColorEnhancementNew instance = new ColorEnhancementNew();
        ColorEnhancementNewFolders.IntelRGraphicsControlPanelAppFolder _intelrgraphicscontrolpanel;

        /// <summary>
        /// Gets the singleton class instance representing the ColorEnhancementNew element repository.
        /// </summary>
        [RepositoryFolder("7304a53c-6fde-4827-8ad0-8f3e0ffaf05d")]
        public static ColorEnhancementNew Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ColorEnhancementNew() 
            : base("ColorEnhancementNew", "", null, 30000, false, "7304a53c-6fde-4827-8ad0-8f3e0ffaf05d", ".\\RepositoryImages\\DisplayTabNewCUI7304a53c.rximgres")
        {
            _intelrgraphicscontrolpanel = new ColorEnhancementNewFolders.IntelRGraphicsControlPanelAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The IntelRGraphicsControlPanel folder.
        /// </summary>
        [RepositoryFolder("a31b6116-903d-4f47-877b-7bb4f8019312")]
        public virtual ColorEnhancementNewFolders.IntelRGraphicsControlPanelAppFolder IntelRGraphicsControlPanel
        {
            get { return _intelrgraphicscontrolpanel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.2")]
    public partial class ColorEnhancementNewFolders
    {
        /// <summary>
        /// The IntelRGraphicsControlPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("a31b6116-903d-4f47-877b-7bb4f8019312")]
        public partial class IntelRGraphicsControlPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _slidernameInfo;

            /// <summary>
            /// Creates a new IntelRGraphicsControlPanel  folder.
            /// </summary>
            public IntelRGraphicsControlPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IntelRGraphicsControlPanel", "/form[@automationid='MainWindow']", parentFolder, 30000, true, "a31b6116-903d-4f47-877b-7bb4f8019312", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "a31b6116-903d-4f47-877b-7bb4f8019312");
                _slidernameInfo = new RepoItemInfo(this, "SliderName", "element/element[@classname='DisplaySettingsWindow']/element[@classname='DisplayColorControl']/element[@automationid='sliderGamma']/slider", 5000, null, "1be4f41c-f2fa-46de-acec-9d3512dd7455");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a31b6116-903d-4f47-877b-7bb4f8019312")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a31b6116-903d-4f47-877b-7bb4f8019312")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SliderName item.
            /// </summary>
            [RepositoryItem("1be4f41c-f2fa-46de-acec-9d3512dd7455")]
            public virtual Ranorex.Slider SliderName
            {
                get
                {
                    try
                    {
                        return _slidernameInfo.CreateAdapter<Ranorex.Slider>(true);
                    }
                    catch
                    {
                        return ColorEnhancementRepo.Instance.FormIntelR_Graphics_and_Medi.SliderGamma;
                    }
                }
            }

            /// <summary>
            /// The SliderName item info.
            /// </summary>
            [RepositoryItemInfo("1be4f41c-f2fa-46de-acec-9d3512dd7455")]
            public virtual RepoItemInfo SliderNameInfo
            {
                get
                {
                    return _slidernameInfo;
                }
            }
        }

    }
}