//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ACPI_OP_REGION.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ACPI_OP_REGION_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LID                  129
#define IDD_DIALOG_DRDY                 130
#define IDD_DIALOG_CSTS                 131
#define IDD_DIALOG_CEVT                 132
#define IDD_DIALOG_DIDL                 133
#define IDD_DIALOG_cpdl                 134
#define IDD_DIALOG_CPDL                 134
#define IDD_DIALOG_CADL                 135
#define IDD_DIALOG_NADL                 136
#define IDD_DIALOG_TIDX                 138
#define IDD_DIALOG_CHPD                 139
#define IDD_DIALOG_CLID                 140
#define IDD_DIALOG_CDCK                 141
#define IDD_DIALOG_NRDY                 142
#define IDR_MENU_MAIN                   143
#define IDD_DIALOG_ARDY                 143
#define IDD_DIALOG_TCHE                 144
#define IDD_DIALOG_CBLV                 145
#define IDD_DIALOG_ASLC                 146
#define IDD_DIALOG_ASLI                 147
#define IDD_DIALOG_BCLP                 148
#define IDD_DIALOG_PFIT                 149
#define IDD_DIALOG_BCLP1                150
#define IDD_DIALOG_ASLP                 150
#define IDD_DIALOG_ASLC1                151
#define IDD_DIALOG_DGS                  151
#define IDD_DIALOG_DGS_NEW              151
#define IDD_DIALOG_DOS                  152
#define IDD_DIALOG_DOS1                 153
#define IDD_DIALOG_DSS                  153
#define IDD_DIALOG_DGS1                 154
#define IDD_DIALOG_BCL                  154
#define IDD_DIALOG_DGS_CTRL             155
#define IDD_DIALOG_LID_SEQ              156
#define IDD_DIALOG_BCM_CTRL             157
#define IDD_DIALOG_DSS_CTRL             158
#define IDD_DIALOG_DOD_CTRL             159
#define IDD_DIALOG_SEQ_HKEY             160
#define IDC_MAINFRAME                   1001
#define IDC_CLID_LABEL                  1003
#define IDC_EDIT1                       1004
#define IDC_TREE_CTRL                   1005
#define IDC_TREE1                       1006
#define IDC_LIST_CPDL                   1009
#define IDC_STATIC_ASLP                 1011
#define IDC_LIST_ASLP                   1012
#define IDC_EDIT_ASLP                   1013
#define IDC_STATIC_CPDL                 1014
#define IDC_COMBO_CDCK                  1017
#define IDC_STATIC_CEVT                 1018
#define IDC_STATIC_CEVT1                1019
#define IDC_COMBO_CEVT                  1020
#define IDC_STATIC_CHPD                 1021
#define IDC_STATIC_CHPD1                1022
#define IDC_COMBO_CHPD                  1023
#define IDC_STATIC_CLID                 1024
#define IDC_STATIC_CLID1                1025
#define IDC_EDIT_CPDL                   1027
#define IDC_STATIC_CSTS                 1028
#define IDC_STATIC_CSTS1                1029
#define IDC_COMBO_CSTS                  1030
#define IDC_STATIC_DIDL                 1031
#define IDC_STATIC_CSTS2                1031
#define IDC_COMBO_CSTS2                 1032
#define IDC_COMBO_DRDY                  1034
#define IDC_STATIC_DRDY                 1035
#define IDC_COMBO_DSS_CTRL1             1035
#define IDC_STATIC_DRDY1                1036
#define IDC_STATIC_NADL                 1037
#define IDC_STATIC_BLC                  1037
#define IDC_LIST_NADL                   1038
#define IDC_COMBO_BLC                   1038
#define IDC_EDIT_NADL                   1039
#define IDC_STATIC_PFIT                 1039
#define IDC_STATIC_NRDY                 1040
#define IDC_COMBO_PFIT                  1040
#define IDC_STATIC_NRDY1                1041
#define IDC_COMBO_NRDY                  1042
#define IDC_STATIC_TIDX                 1043
#define IDC_STATIC_TIDX1                1044
#define IDC_COMBO_TIDX                  1045
#define IDC_BUTTON_REFRESH              1046
#define IDC_BUTTON_LOAD                 1047
#define IDC_BUTTON_SAVE                 1048
#define IDC_COMBO_ARDY                  1049
#define IDC_STATIC_ALS                  1050
#define IDC_COMBO_ALS                   1051
#define IDC_STATIC_CBLV                 1052
#define IDC_COMBO_CBLV                  1053
#define IDC_STATIC_CBLV1                1054
#define IDC_STATIC_ASLC_ALS             1055
#define IDC_STATIC_ASLC_BLC             1056
#define IDC_STATIC_ASLC_PFIT            1057
#define IDC_COMBO_ALSC_ALS              1058
#define IDC_COMBO_ALSC_BLC              1059
#define IDC_COMBO_ALSC_PFIT             1060
#define IDC_STATIC_PFIT1                1064
#define IDC_STATIC_PFIT2                1065
#define IDC_STATIC_PFIT3                1066
#define IDC_STATIC_PFIT4                1067
#define IDC_COMBO_PFIT_CNTR             1068
#define IDC_COMBO_PFIT_STR              1069
#define IDC_COMBO_PFIT_GRMS             1070
#define IDC_STATIC_ASLP1                1071
#define IDC_DGS_LIST                    1072
#define IDC_BCL_LIST                    1072
#define IDC_DGS_LIST_CT                 1072
#define IDC_STATIC_DOS1                 1073
#define IDC_STATIC_DOS2                 1074
#define IDC_COMBO_DOS1                  1075
#define IDC_COMBO_DOS2                  1076
#define IDC_BUTTON1                     1077
#define IDC_LIST_BCL                    1078
#define IDC_STATIC_BCL1                 1079
#define IDC_STATIC_Dod                  1080
#define IDC_EDIT_DOD                    1081
#define IDC_EDIT_DIDL                   1081
#define IDC_COMBO_BQC                   1082
#define IDC_COMBO_CLID                  1082
#define IDC_STATIC_BCM1                 1084
#define IDC_LIST1                       1085
#define IDC_STATIC_BCM_CTRL             1086
#define IDC_STATIC_BCM_CTRL1            1087
#define IDC_COMBO_BCM_CTRL              1088
#define IDC_LIST_DOD                    1089
#define IDC_EDIT_DOD_CRTL               1090
#define IDC_STATIC_DSS_CRTL             1091
#define IDC_COMBO_DSS_CRTL2             1092
#define IDC_SEQ_HKEY_CTRL               1093
#define ID_FILE_EXIT                    32771
#define ID_OPTIONS_READFROMSYSTEM       32772
#define ID_FILE_SAVE32773               32773
#define ID_FILE_EXIT32774               32774
#define ID_HELP_ABOUTACPIOPREGIONEDITOR 32775
#define ID_OPTIONS_REFRESHOPREGION      32776
#define ID_LOAD_FROMFILE                32777
#define ID_LOAD_FROMSYSTEM              32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
