namespace Intel.VPG.Display.Automation
{
    public enum Features
    {
        //AccessAPI::
        //-> ExternalAssemblies
        PowerEvent,
        WindowsMonitorID,
        DisplayEnumeration,
        ACPIFunctions,
        InstallDDriver,
        CursorEvent,
        MonitorTurnOff,
        ForceTDR,
        XvYcc,
        YCbCr,
        AddToRegistry,
        MDRRS_48Hz,
        MoveCursor,
        LidSwitch,
        QuantizationRange,
        SetUpDesktop,
        ImageProcessing,
        RegistryInf,
        PSR1,
        PSR2,
        DSR,
        PanelBLCInfo,
        PanelBrightnessControl,
        //-> Common
        CaptureScreenImage,
        WinSystemInformation,        
        CPUState,
        NetworkConnection,
        PromptMessage,
        SocWatch,
        VerifySystemState,
        VerifyUnderrun,
        //-> Display
        Config,
        Bpp,
        Resolution, 
        Modes,
        Rotation,
        WIGIG,
        CRC,
        CrcGoldenData,
        StaticForm,
        VerifyCRC,
        PowerWell,

        //-> Audio
        ChangeAudioSource,
        AudioEnumeration,

        //-> Driver
        DisableDriver,
        DriverVerifier,
        EnableDriver,
        InstallDriver,
        UnInstallDriver,
        UpgradeDriver,
        DriverFunction,
        DeviceStatus,
        NonPnPDriverRoutine,

        //-> SDK
        SDKDisplayEnumeration,
        SdkIndependentRotation,
        NarrowGamut,
        DpcdRegister,
        SDKConfig,
        Collage,

        //-> DVMU
        InfoFrameParsing,
        DvmuHotPlugStatus,
        SimulatedHotPlugDisplay,
        // -> Color
        WideGamut,
        DeepColor,
        // -> Escape
        DriverEscape,
        ULT_Framework,
        PipePlane,
        Watermark,
        EventRegisterInfo,
        // -> Video
        Overlay,
        PLL,
        YTiling,
        DBuf,
        //AccessUI::
        //-> Common
        NotificationAreaIcons,
        WiDiDisplayConnection,
        //-> Features
        AppBar,
        ConfirmationPopup,
        CUIHeaderOptions,
        LaunchCUI,
        LaunchApp,
        LaunchCharmWindow,
        HDCP,
        EDIDData,
        //-> Display
        DisplayConfig,
        ComboBoxConfig,
        ComboBoxEnableDisableCollage,
        HorizontalVerticalCollage,
        EnableDisableCollage,
        ChoosePrimaryDisplay,
        ChooseSecondaryDisplay,
        ChooseTertiaryDisplay,
        SetDisplayFullName,
        RefreshRate,
        Scaling,
        SelectDisplay,
        SelectDisplayInfo,
        ColorDepth,
        EnableCollage,
        DisplaySettings,
        Colour,
        Gamma,
        PlayMPOClip,
        XvyccYcbcr,
        //-> Options
        SystemInfo,
        ConnectorType,
        DeviceType,
        //-> DTCM
        DTCMFeature,
        DTCMShowDesktop,
        Graphics_Properties,
        DTCMTrayIcon,
        DTCMSingleConfig,
        DTCMCloneConfig,
        DTCMExtendConfig,
        DTCMHotKeys,
        //EnvironmentInit::
        InitRebootAnalysis,
        InitVerifyDriverStatus,
        InitClearDumpsNEvents,
        InitClearCUI,
        InitAssemblies,
        InitEnumerateDisplays,
        InitPlugDVMUDisplays,
        InitMetroSkip,
        InitCheckDriverVerify,
        InitVerifyDotNetFW,
        InitVerifyDivaStatus,
        InitPlugSimulatedDisplays,
        InitCleanupSimulatedDisplays,
        InitCloneDriver,
        InitHotplugFramework,
        InitDisableLAN,
        InitEnableCommonRoutine,
        InitTestCleanUp,

        Chronometer,
        Run,
        Start,
        //S0ix
        ConnectedStandby,
        ThreeDBasicSettingFeatures,
        VideoBasicSettingFeatures
    }
}
