///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Intel.VPG.Display.Automation
{
    /// <summary>
    /// The class representing the AntiAliasingRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.2")]
    [RepositoryFolder("7304a53c-6fde-4827-8ad0-8f3e0ffaf05d")]
    public partial class AntiAliasingRepo : RepoGenBaseFolder
    {
        static AntiAliasingRepo instance = new AntiAliasingRepo();
        AntiAliasingRepoFolders.IntelRGraphicsControlPanelAppFolder _intelrgraphicscontrolpanel;

        /// <summary>
        /// Gets the singleton class instance representing the AntiAliasingRepo element repository.
        /// </summary>
        [RepositoryFolder("7304a53c-6fde-4827-8ad0-8f3e0ffaf05d")]
        public static AntiAliasingRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AntiAliasingRepo() 
            : base("AntiAliasingRepo", "", null, 30000, false, "7304a53c-6fde-4827-8ad0-8f3e0ffaf05d", ".\\RepositoryImages\\DisplayTabNewCUI7304a53c.rximgres")
        {
            _intelrgraphicscontrolpanel = new AntiAliasingRepoFolders.IntelRGraphicsControlPanelAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The IntelRGraphicsControlPanel folder.
        /// </summary>
        [RepositoryFolder("5d6c7462-dbc7-45b9-bd43-795cd9239099")]
        public virtual AntiAliasingRepoFolders.IntelRGraphicsControlPanelAppFolder IntelRGraphicsControlPanel
        {
            get { return _intelrgraphicscontrolpanel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.2")]
    public partial class AntiAliasingRepoFolders
    {
        /// <summary>
        /// The IntelRGraphicsControlPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("5d6c7462-dbc7-45b9-bd43-795cd9239099")]
        public partial class IntelRGraphicsControlPanelAppFolder : RepoGenBaseFolder
        {
            AntiAliasingRepoFolders.DisplayMainPageFolder _displaymainpage;
            RepoItemInfo _selfInfo;

            /// <summary>
            /// Creates a new IntelRGraphicsControlPanel  folder.
            /// </summary>
            public IntelRGraphicsControlPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IntelRGraphicsControlPanel", "/form[@automationid='MainWindow']", parentFolder, 30000, true, "5d6c7462-dbc7-45b9-bd43-795cd9239099", "")
            {
                _displaymainpage = new AntiAliasingRepoFolders.DisplayMainPageFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5d6c7462-dbc7-45b9-bd43-795cd9239099");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5d6c7462-dbc7-45b9-bd43-795cd9239099")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5d6c7462-dbc7-45b9-bd43-795cd9239099")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DisplayMainPage folder.
            /// </summary>
            [RepositoryFolder("196d925d-23f6-4273-96fe-6beea1284c93")]
            public virtual AntiAliasingRepoFolders.DisplayMainPageFolder DisplayMainPage
            {
                get { return _displaymainpage; }
            }
        }

        /// <summary>
        /// The DisplayMainPageFolder folder.
        /// </summary>
        [RepositoryFolder("196d925d-23f6-4273-96fe-6beea1284c93")]
        public partial class DisplayMainPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _displayfeaturestabcontrolInfo;
            RepoItemInfo _colorsettings1Info;
            RepoItemInfo _colorsettingsInfo;
            RepoItemInfo _displaysettings1Info;
            RepoItemInfo _displaysettingsInfo;

            /// <summary>
            /// Creates a new DisplayMainPage  folder.
            /// </summary>
            public DisplayMainPageFolder(RepoGenBaseFolder parentFolder) :
                    base("DisplayMainPage", "element", parentFolder, 30000, true, "196d925d-23f6-4273-96fe-6beea1284c93", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "196d925d-23f6-4273-96fe-6beea1284c93");
                _displayfeaturestabcontrolInfo = new RepoItemInfo(this, "DisplayFeaturesTabControl", "element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']", 30000, null, "b458fd0e-5a9d-4106-a99a-5250ab7c7754");
                _colorsettings1Info = new RepoItemInfo(this, "ColorSettings1", "element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Color Settings']", 5000, null, "960bd585-d5a0-4631-ba03-e39248f3583d");
                _colorsettingsInfo = new RepoItemInfo(this, "ColorSettings", "element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Color Settings']/text[@automationid='text']", 30000, null, "625ac36a-74b1-441b-8144-a76c01b5dff4");
                _displaysettings1Info = new RepoItemInfo(this, "DisplaySettings1", "element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Display Settings']", 30000, null, "023df9b0-ccfe-42a7-a2bf-6871dc671ed4");
                _displaysettingsInfo = new RepoItemInfo(this, "DisplaySettings", "element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Display Settings']/text[@automationid='text']", 30000, null, "e451a5f1-76b6-4b54-8132-bc2bd1bab615");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("196d925d-23f6-4273-96fe-6beea1284c93")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("196d925d-23f6-4273-96fe-6beea1284c93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DisplayFeaturesTabControl item.
            /// </summary>
            [RepositoryItem("b458fd0e-5a9d-4106-a99a-5250ab7c7754")]
            public virtual Ranorex.Unknown DisplayFeaturesTabControl
            {
                get
                {
                    return _displayfeaturestabcontrolInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DisplayFeaturesTabControl item info.
            /// </summary>
            [RepositoryItemInfo("b458fd0e-5a9d-4106-a99a-5250ab7c7754")]
            public virtual RepoItemInfo DisplayFeaturesTabControlInfo
            {
                get
                {
                    return _displayfeaturestabcontrolInfo;
                }
            }

            /// <summary>
            /// The ColorSettings1 item.
            /// </summary>
            [RepositoryItem("960bd585-d5a0-4631-ba03-e39248f3583d")]
            public virtual Ranorex.RadioButton ColorSettings1
            {
                get
                {
                    try
                    {
                        return _colorsettings1Info.CreateAdapter<Ranorex.RadioButton>(true);
                    }
                    catch
                    {
                       return DisplayTabsRepo.Instance.IntelRHDGraphicsControlPanel.Color;
                    }
                }
            }

            /// <summary>
            /// The ColorSettings1 item info.
            /// </summary>
            [RepositoryItemInfo("960bd585-d5a0-4631-ba03-e39248f3583d")]
            public virtual RepoItemInfo ColorSettings1Info
            {
                get
                {
                    return _colorsettings1Info;
                }
            }

            /// <summary>
            /// The ColorSettings item.
            /// </summary>
            [RepositoryItem("625ac36a-74b1-441b-8144-a76c01b5dff4")]
            public virtual Ranorex.Text ColorSettings
            {
                get
                {
                    return _colorsettingsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ColorSettings item info.
            /// </summary>
            [RepositoryItemInfo("625ac36a-74b1-441b-8144-a76c01b5dff4")]
            public virtual RepoItemInfo ColorSettingsInfo
            {
                get
                {
                    return _colorsettingsInfo;
                }
            }

            /// <summary>
            /// The DisplaySettings1 item.
            /// </summary>
            [RepositoryItem("023df9b0-ccfe-42a7-a2bf-6871dc671ed4")]
            public virtual Ranorex.RadioButton DisplaySettings1
            {
                get
                {
                    return _displaysettings1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The DisplaySettings1 item info.
            /// </summary>
            [RepositoryItemInfo("023df9b0-ccfe-42a7-a2bf-6871dc671ed4")]
            public virtual RepoItemInfo DisplaySettings1Info
            {
                get
                {
                    return _displaysettings1Info;
                }
            }

            /// <summary>
            /// The DisplaySettings item.
            /// </summary>
            [RepositoryItem("e451a5f1-76b6-4b54-8132-bc2bd1bab615")]
            public virtual Ranorex.Text DisplaySettings
            {
                get
                {
                    return _displaysettingsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DisplaySettings item info.
            /// </summary>
            [RepositoryItemInfo("e451a5f1-76b6-4b54-8132-bc2bd1bab615")]
            public virtual RepoItemInfo DisplaySettingsInfo
            {
                get
                {
                    return _displaysettingsInfo;
                }
            }
        }

    }
}