///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Intel.VPG.Display.Automation
{
    /// <summary>
    /// The class representing the DisplayTabsRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.4")]
    [RepositoryFolder("6e7c3829-4b74-4d85-b559-351714ccbda2")]
    public partial class DisplayTabsRepo : RepoGenBaseFolder
    {
        static DisplayTabsRepo instance = new DisplayTabsRepo();
        DisplayTabsRepoFolders.IntelRHDGraphicsControlPanelAppFolder _intelrhdgraphicscontrolpanel;

        /// <summary>
        /// Gets the singleton class instance representing the DisplayTabsRepo element repository.
        /// </summary>
        [RepositoryFolder("6e7c3829-4b74-4d85-b559-351714ccbda2")]
        public static DisplayTabsRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DisplayTabsRepo()
            : base("DisplayTabsRepo", "", null, 30000, false, "6e7c3829-4b74-4d85-b559-351714ccbda2", ".\\RepositoryImages\\NewRepository6e7c3829.rximgres")
        {
            _intelrhdgraphicscontrolpanel = new DisplayTabsRepoFolders.IntelRHDGraphicsControlPanelAppFolder(this);
        }

        #region Variables

        #endregion

        /// <summary>
        /// The IntelRHDGraphicsControlPanel folder.
        /// </summary>
        [RepositoryFolder("5318f380-7594-4caa-a5e7-f5f103119b6b")]
        public virtual DisplayTabsRepoFolders.IntelRHDGraphicsControlPanelAppFolder IntelRHDGraphicsControlPanel
        {
            get { return _intelrhdgraphicscontrolpanel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.4")]
    public partial class DisplayTabsRepoFolders
    {
        /// <summary>
        /// The IntelRHDGraphicsControlPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("5318f380-7594-4caa-a5e7-f5f103119b6b")]
        public partial class IntelRHDGraphicsControlPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _colorInfo;
            RepoItemInfo _displaysettingsInfo;
            RepoItemInfo _horizontallist0Info;
            RepoItemInfo _horizontallist1Info;

            /// <summary>
            /// Creates a new IntelRHDGraphicsControlPanel  folder.
            /// </summary>
            public IntelRHDGraphicsControlPanelAppFolder(RepoGenBaseFolder parentFolder) :
                base("IntelRHDGraphicsControlPanel", "/form[@automationid='MainWindow']", parentFolder, 30000, true, "5318f380-7594-4caa-a5e7-f5f103119b6b", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5318f380-7594-4caa-a5e7-f5f103119b6b");
                _colorInfo = new RepoItemInfo(this, "Color", "element/element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Color']", 5000, null, "2b1f1777-583c-4c40-b37e-cac9965e203d");
                _displaysettingsInfo = new RepoItemInfo(this, "DisplaySettings", "element/element[@classname='DisplaySettingsWindow']/element[@automationid='DisplayFeaturesTabControl']/radiobutton[@name='Display Settings']", 30000, null, "b8def8a6-434c-4c61-8c8f-cc9df128b433");
                _horizontallist0Info = new RepoItemInfo(this, "HorizontalList0", "element/element[@classname='DisplaySettingsWindow']/element[@classname='DisplayGeneralSettingsControl']/element[@automationid='basicAdvOptions']/element[@automationid='HorizontalList_0']", 30000, null, "d3075988-115d-481d-93f0-98deddcd9f75");
                _horizontallist1Info = new RepoItemInfo(this, "HorizontalList1", "element/element[@classname='DisplaySettingsWindow']/element[@classname='DisplayGeneralSettingsControl']/element[@automationid='basicAdvOptions']/element[@automationid='HorizontalList_1']", 30000, null, "d0811bb3-b591-4b5d-bb22-0f2dca9b9d23");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5318f380-7594-4caa-a5e7-f5f103119b6b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5318f380-7594-4caa-a5e7-f5f103119b6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("2b1f1777-583c-4c40-b37e-cac9965e203d")]
            public virtual Ranorex.RadioButton Color
            {
                get
                {
                    try
                    {
                        return _colorInfo.CreateAdapter<Ranorex.RadioButton>(true);
                    }
                    catch
                    {
                        return AntiAliasingRepo.Instance.IntelRGraphicsControlPanel.DisplayMainPage.ColorSettings1;
                    }
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("2b1f1777-583c-4c40-b37e-cac9965e203d")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The DisplaySettings item.
            /// </summary>
            [RepositoryItem("b8def8a6-434c-4c61-8c8f-cc9df128b433")]
            public virtual Ranorex.RadioButton DisplaySettings
            {
                get
                {
                    try
                    {
                        return _displaysettingsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                    }
                    catch
                    {
                        return AntiAliasingRepo.Instance.IntelRGraphicsControlPanel.DisplayMainPage.DisplaySettings1;
                    }
                }
            }

            /// <summary>
            /// The DisplaySettings item info.
            /// </summary>
            [RepositoryItemInfo("b8def8a6-434c-4c61-8c8f-cc9df128b433")]
            public virtual RepoItemInfo DisplaySettingsInfo
            {
                get
                {
                    return _displaysettingsInfo;
                }
            }

            /// <summary>
            /// The HorizontalList0 item.
            /// </summary>
            [RepositoryItem("d3075988-115d-481d-93f0-98deddcd9f75")]
            public virtual Ranorex.Unknown HorizontalList0
            {
                get
                {
                    return _horizontallist0Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The HorizontalList0 item info.
            /// </summary>
            [RepositoryItemInfo("d3075988-115d-481d-93f0-98deddcd9f75")]
            public virtual RepoItemInfo HorizontalList0Info
            {
                get
                {
                    return _horizontallist0Info;
                }
            }

            /// <summary>
            /// The HorizontalList1 item.
            /// </summary>
            [RepositoryItem("d0811bb3-b591-4b5d-bb22-0f2dca9b9d23")]
            public virtual Ranorex.Unknown HorizontalList1
            {
                get
                {
                    return _horizontallist1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The HorizontalList1 item info.
            /// </summary>
            [RepositoryItemInfo("d0811bb3-b591-4b5d-bb22-0f2dca9b9d23")]
            public virtual RepoItemInfo HorizontalList1Info
            {
                get
                {
                    return _horizontallist1Info;
                }
            }
        }

    }
}