######################################################################################################################
# @file         dsc_cfg_rc_range_params.py
# @brief        Contains RC Range Parameters that are from .cfg files provides with VESA C-Model
#               Values from this file will be used only if the display is Mipi or is the total pixels in the slice is
#               less than 15000
#
# @author       Praburaj Krishnan
#######################################################################################################################

from typing import Dict

from Libs.Feature.vdsc.dsc_definitions import RCRangeParametersFromCFG, RcRangeParameters

##
# BPC to rc param mapping
RC_PARAM_ROW_INDEX: Dict[int, int] = {
    6: 0,
    8: 1,
    10: 2,
    12: 3,
    15: 4
}

##
# BPP to rc param mapping
RC_PARAM_COL_INDEX: Dict[int, int] = {
    8: 0,
    10: 1,
    12: 2,
    14: 3,
    16: 4
}

RC_PARAMETERS = [
    # 6BPP
    [
        # 6BPP/8BPC
        RCRangeParametersFromCFG(768, 15, 6144, 3, 13, 11, 11,
                                 [RcRangeParameters(0, 4, 0),
                                  RcRangeParameters(1, 6, -2),
                                  RcRangeParameters(3, 8, -2),
                                  RcRangeParameters(4, 8, -4),
                                  RcRangeParameters(5, 9, -6),
                                  RcRangeParameters(5, 9, -6),
                                  RcRangeParameters(6, 9, -6),
                                  RcRangeParameters(6, 10, -8),
                                  RcRangeParameters(7, 11, -8),
                                  RcRangeParameters(8, 12, -10),
                                  RcRangeParameters(9, 12, -10),
                                  RcRangeParameters(10, 12, -12),
                                  RcRangeParameters(10, 12, -12),
                                  RcRangeParameters(11, 12, -12),
                                  RcRangeParameters(13, 14, -12)]),

        # 6BPP/10BPC
        RCRangeParametersFromCFG(768, 15, 6144, 7, 17, 15, 15,
                                 [RcRangeParameters(0, 8, 0),
                                  RcRangeParameters(3, 10, -2),
                                  RcRangeParameters(7, 12, -2),
                                  RcRangeParameters(8, 12, -4),
                                  RcRangeParameters(9, 13, -6),
                                  RcRangeParameters(9, 13, -6),
                                  RcRangeParameters(10, 13, -6),
                                  RcRangeParameters(10, 14, -8),
                                  RcRangeParameters(11, 15, -8),
                                  RcRangeParameters(12, 16, -10),
                                  RcRangeParameters(13, 16, -10),
                                  RcRangeParameters(14, 16, -12),
                                  RcRangeParameters(14, 16, -12),
                                  RcRangeParameters(15, 16, -12),
                                  RcRangeParameters(17, 18, -12)]),

        # 6BPP/12BPC
        RCRangeParametersFromCFG(768, 15, 6144, 11, 21, 19, 19,
                                 [RcRangeParameters(0, 12, 0),
                                  RcRangeParameters(5, 14, -2),
                                  RcRangeParameters(11, 16, -2),
                                  RcRangeParameters(12, 16, -4),
                                  RcRangeParameters(13, 17, -6),
                                  RcRangeParameters(13, 17, -6),
                                  RcRangeParameters(14, 17, -6),
                                  RcRangeParameters(14, 18, -8),
                                  RcRangeParameters(15, 19, -8),
                                  RcRangeParameters(16, 20, -10),
                                  RcRangeParameters(17, 20, -10),
                                  RcRangeParameters(18, 20, -12),
                                  RcRangeParameters(18, 20, -12),
                                  RcRangeParameters(19, 20, -12),
                                  RcRangeParameters(21, 22, -12)]),

        # 6BPP/14BPC
        RCRangeParametersFromCFG(768, 15, 6144, 15, 25, 23, 27,
                                 [RcRangeParameters(0, 16, 0),
                                  RcRangeParameters(7, 18, -2),
                                  RcRangeParameters(15, 20, -2),
                                  RcRangeParameters(16, 20, -4),
                                  RcRangeParameters(17, 21, -6),
                                  RcRangeParameters(17, 21, -6),
                                  RcRangeParameters(18, 21, -6),
                                  RcRangeParameters(18, 22, -8),
                                  RcRangeParameters(19, 23, -8),
                                  RcRangeParameters(20, 24, -10),
                                  RcRangeParameters(21, 24, -10),
                                  RcRangeParameters(22, 24, -12),
                                  RcRangeParameters(22, 24, -12),
                                  RcRangeParameters(23, 24, -12),
                                  RcRangeParameters(25, 26, -12)]),

        # 6BPP/16BPC
        RCRangeParametersFromCFG(768, 15, 6144, 19, 29, 27, 27,
                                 [RcRangeParameters(0, 20, 0),
                                  RcRangeParameters(9, 22, -2),
                                  RcRangeParameters(19, 24, -2),
                                  RcRangeParameters(20, 24, -4),
                                  RcRangeParameters(21, 25, -6),
                                  RcRangeParameters(21, 25, -6),
                                  RcRangeParameters(22, 25, -6),
                                  RcRangeParameters(22, 26, -8),
                                  RcRangeParameters(23, 27, -8),
                                  RcRangeParameters(24, 28, -10),
                                  RcRangeParameters(25, 28, -10),
                                  RcRangeParameters(26, 28, -12),
                                  RcRangeParameters(26, 28, -12),
                                  RcRangeParameters(27, 28, -12),
                                  RcRangeParameters(29, 30, -12)]),
    ],

    # 8BPP
    [
        # 8BPP/8BPC
        RCRangeParametersFromCFG(512, 12, 6144, 3, 12, 11, 11,
                                 [RcRangeParameters(0, 4, 2),
                                  RcRangeParameters(0, 4, 0),
                                  RcRangeParameters(1, 5, 0),
                                  RcRangeParameters(1, 6, -2),
                                  RcRangeParameters(3, 7, -4),
                                  RcRangeParameters(3, 7, -6),
                                  RcRangeParameters(3, 7, -8),
                                  RcRangeParameters(3, 8, -8),
                                  RcRangeParameters(3, 9, -8),
                                  RcRangeParameters(3, 10, -10),
                                  RcRangeParameters(5, 11, -10),
                                  RcRangeParameters(5, 12, -12),
                                  RcRangeParameters(5, 13, -12),
                                  RcRangeParameters(7, 13, -12),
                                  RcRangeParameters(13, 15, -12)]),

        # 8BPP/10BPC
        RCRangeParametersFromCFG(512, 12, 6144, 7, 16, 15, 15,
                                 [RcRangeParameters(0, 4, 2),
                                  RcRangeParameters(4, 8, 0),
                                  RcRangeParameters(5, 9, 0),
                                  RcRangeParameters(5, 10, -2),
                                  RcRangeParameters(7, 11, -4),
                                  RcRangeParameters(7, 11, -6),
                                  RcRangeParameters(7, 11, -8),
                                  RcRangeParameters(7, 12, -8),
                                  RcRangeParameters(7, 13, -8),
                                  RcRangeParameters(7, 14, -10),
                                  RcRangeParameters(9, 15, -10),
                                  RcRangeParameters(9, 16, -12),
                                  RcRangeParameters(9, 17, -12),
                                  RcRangeParameters(11, 17, -12),
                                  RcRangeParameters(17, 19, -12)]),

        # 8BPP/12BPC
        RCRangeParametersFromCFG(512, 12, 6144, 11, 20, 19, 19,
                                 [RcRangeParameters(0, 12, 2),
                                  RcRangeParameters(4, 12, 0),
                                  RcRangeParameters(9, 13, 0),
                                  RcRangeParameters(9, 14, -2),
                                  RcRangeParameters(11, 15, -4),
                                  RcRangeParameters(11, 15, -6),
                                  RcRangeParameters(11, 15, -8),
                                  RcRangeParameters(11, 16, -8),
                                  RcRangeParameters(11, 17, -8),
                                  RcRangeParameters(11, 18, -10),
                                  RcRangeParameters(13, 19, -10),
                                  RcRangeParameters(13, 20, -12),
                                  RcRangeParameters(13, 21, -12),
                                  RcRangeParameters(15, 21, -12),
                                  RcRangeParameters(21, 23, -12)]),

        # 8BPP/14BPC
        RCRangeParametersFromCFG(512, 12, 6144, 15, 24, 23, 23,
                                 [RcRangeParameters(0, 12, 0),
                                  RcRangeParameters(5, 13, 0),
                                  RcRangeParameters(11, 15, 0),
                                  RcRangeParameters(12, 17, -2),
                                  RcRangeParameters(15, 19, -4),
                                  RcRangeParameters(15, 19, -6),
                                  RcRangeParameters(15, 19, -8),
                                  RcRangeParameters(15, 20, -8),
                                  RcRangeParameters(15, 21, -8),
                                  RcRangeParameters(15, 22, -10),
                                  RcRangeParameters(17, 22, -10),
                                  RcRangeParameters(17, 23, -12),
                                  RcRangeParameters(17, 23, -12),
                                  RcRangeParameters(21, 24, -12),
                                  RcRangeParameters(24, 25, -12)]),

        # 8BPP/16BPC
        RCRangeParametersFromCFG(512, 12, 6144, 19, 28, 27, 27,
                                 [RcRangeParameters(0, 12, 2),
                                  RcRangeParameters(6, 14, 0),
                                  RcRangeParameters(13, 17, 0),
                                  RcRangeParameters(15, 20, -2),
                                  RcRangeParameters(19, 23, -4),
                                  RcRangeParameters(19, 23, -6),
                                  RcRangeParameters(19, 23, -8),
                                  RcRangeParameters(19, 24, -8),
                                  RcRangeParameters(19, 25, -8),
                                  RcRangeParameters(19, 26, -10),
                                  RcRangeParameters(21, 26, -10),
                                  RcRangeParameters(21, 27, -12),
                                  RcRangeParameters(21, 27, -12),
                                  RcRangeParameters(25, 28, -12),
                                  RcRangeParameters(28, 29, -12)]),
    ],

    # 10BPP
    [
        # 10BPP/8BPC
        RCRangeParametersFromCFG(410, 15, 5632, 3, 12, 11, 11,
                                 [RcRangeParameters(0, 3, 2),
                                  RcRangeParameters(0, 4, 0),
                                  RcRangeParameters(1, 5, 0),
                                  RcRangeParameters(2, 6, -2),
                                  RcRangeParameters(3, 7, -4),
                                  RcRangeParameters(3, 7, -6),
                                  RcRangeParameters(3, 7, -8),
                                  RcRangeParameters(3, 8, -8),
                                  RcRangeParameters(3, 9, -8),
                                  RcRangeParameters(3, 9, -10),
                                  RcRangeParameters(5, 10, -10),
                                  RcRangeParameters(5, 10, -10),
                                  RcRangeParameters(5, 11, -12),
                                  RcRangeParameters(7, 11, -12),
                                  RcRangeParameters(11, 12, -12)]),

        # 10BPP/10BPC
        RCRangeParametersFromCFG(410, 15, 5632, 7, 16, 15, 15,
                                 [RcRangeParameters(0, 7, 2),
                                  RcRangeParameters(4, 8, 0),
                                  RcRangeParameters(5, 9, 0),
                                  RcRangeParameters(6, 10, -2),
                                  RcRangeParameters(7, 11, -4),
                                  RcRangeParameters(7, 11, -6),
                                  RcRangeParameters(7, 11, -8),
                                  RcRangeParameters(7, 12, -8),
                                  RcRangeParameters(7, 13, -8),
                                  RcRangeParameters(7, 13, -10),
                                  RcRangeParameters(9, 14, -10),
                                  RcRangeParameters(9, 14, -10),
                                  RcRangeParameters(9, 15, -12),
                                  RcRangeParameters(11, 15, -12),
                                  RcRangeParameters(15, 16, -12)]),

        # 10BPP/12BPC
        RCRangeParametersFromCFG(410, 15, 5632, 11, 20, 19, 19,
                                 [RcRangeParameters(0, 11, 2),
                                  RcRangeParameters(4, 12, 0),
                                  RcRangeParameters(9, 13, 0),
                                  RcRangeParameters(10, 14, -2),
                                  RcRangeParameters(11, 15, -4),
                                  RcRangeParameters(11, 15, -6),
                                  RcRangeParameters(11, 15, -8),
                                  RcRangeParameters(11, 16, -8),
                                  RcRangeParameters(11, 17, -8),
                                  RcRangeParameters(11, 17, -10),
                                  RcRangeParameters(13, 18, -10),
                                  RcRangeParameters(13, 18, -10),
                                  RcRangeParameters(13, 19, -12),
                                  RcRangeParameters(15, 19, -12),
                                  RcRangeParameters(19, 20, -12)]),

        # 10BPP/14BPC
        RCRangeParametersFromCFG(410, 15, 5632, 15, 24, 23, 23,
                                 [RcRangeParameters(0, 11, 2),
                                  RcRangeParameters(5, 13, 0),
                                  RcRangeParameters(11, 15, 0),
                                  RcRangeParameters(13, 18, -2),
                                  RcRangeParameters(15, 19, -4),
                                  RcRangeParameters(15, 19, -6),
                                  RcRangeParameters(15, 19, -8),
                                  RcRangeParameters(15, 20, -8),
                                  RcRangeParameters(15, 21, -8),
                                  RcRangeParameters(15, 21, -10),
                                  RcRangeParameters(17, 22, -10),
                                  RcRangeParameters(17, 22, -10),
                                  RcRangeParameters(17, 23, -12),
                                  RcRangeParameters(19, 23, -12),
                                  RcRangeParameters(23, 24, -12)]),

        # 10BPP/16BPC
        RCRangeParametersFromCFG(410, 15, 5632, 19, 28, 27, 27,
                                 [RcRangeParameters(0, 11, 2),
                                  RcRangeParameters(6, 14, 0),
                                  RcRangeParameters(13, 17, 0),
                                  RcRangeParameters(16, 20, -2),
                                  RcRangeParameters(19, 23, -4),
                                  RcRangeParameters(19, 23, -6),
                                  RcRangeParameters(19, 23, -8),
                                  RcRangeParameters(19, 24, -8),
                                  RcRangeParameters(19, 25, -8),
                                  RcRangeParameters(19, 25, -10),
                                  RcRangeParameters(21, 26, -10),
                                  RcRangeParameters(21, 26, -10),
                                  RcRangeParameters(21, 27, -12),
                                  RcRangeParameters(23, 27, -12),
                                  RcRangeParameters(27, 28, -12)]),

    ],

    # 12BPP
    [
        # 12BPP/8BPC
        RCRangeParametersFromCFG(341, 15, 2048, 3, 12, 11, 11,
                                 [RcRangeParameters(0, 2, 2),
                                  RcRangeParameters(0, 4, 0),
                                  RcRangeParameters(1, 5, 0),
                                  RcRangeParameters(1, 6, -2),
                                  RcRangeParameters(3, 7, -4),
                                  RcRangeParameters(3, 7, -6),
                                  RcRangeParameters(3, 7, -8),
                                  RcRangeParameters(3, 8, -8),
                                  RcRangeParameters(3, 9, -8),
                                  RcRangeParameters(3, 10, -10),
                                  RcRangeParameters(5, 11, -10),
                                  RcRangeParameters(5, 12, -12),
                                  RcRangeParameters(5, 13, -12),
                                  RcRangeParameters(7, 13, -12),
                                  RcRangeParameters(13, 15, -12)]),

        # 12BPP/10BPC
        RCRangeParametersFromCFG(341, 15, 2048, 7, 16, 15, 15,
                                 [RcRangeParameters(0, 2, 2),
                                  RcRangeParameters(2, 5, 0),
                                  RcRangeParameters(3, 7, 0),
                                  RcRangeParameters(4, 8, -2),
                                  RcRangeParameters(6, 9, -4),
                                  RcRangeParameters(7, 10, -6),
                                  RcRangeParameters(7, 11, -8),
                                  RcRangeParameters(7, 12, -8),
                                  RcRangeParameters(7, 13, -8),
                                  RcRangeParameters(7, 14, -10),
                                  RcRangeParameters(9, 15, -10),
                                  RcRangeParameters(9, 16, -12),
                                  RcRangeParameters(9, 17, -12),
                                  RcRangeParameters(11, 17, -12),
                                  RcRangeParameters(17, 19, -12)]),

        # 12BPP/12BPC
        RCRangeParametersFromCFG(341, 15, 2048, 11, 20, 19, 19,
                                 [RcRangeParameters(0, 6, 2),
                                  RcRangeParameters(4, 9, 0),
                                  RcRangeParameters(7, 11, 0),
                                  RcRangeParameters(8, 12, -2),
                                  RcRangeParameters(10, 13, -4),
                                  RcRangeParameters(11, 14, -6),
                                  RcRangeParameters(11, 15, -8),
                                  RcRangeParameters(11, 16, -8),
                                  RcRangeParameters(11, 17, -8),
                                  RcRangeParameters(11, 18, -10),
                                  RcRangeParameters(13, 19, -10),
                                  RcRangeParameters(13, 20, -12),
                                  RcRangeParameters(13, 21, -12),
                                  RcRangeParameters(15, 21, -12),
                                  RcRangeParameters(21, 23, -12)]),

        # 12BPP/14BPC
        RCRangeParametersFromCFG(341, 15, 2048, 15, 24, 23, 23,
                                 [RcRangeParameters(0, 6, 2),
                                  RcRangeParameters(7, 10, 0),
                                  RcRangeParameters(9, 13, 0),
                                  RcRangeParameters(11, 16, -2),
                                  RcRangeParameters(14, 17, -4),
                                  RcRangeParameters(15, 18, -6),
                                  RcRangeParameters(15, 19, -8),
                                  RcRangeParameters(15, 20, -8),
                                  RcRangeParameters(15, 20, -8),
                                  RcRangeParameters(15, 21, -10),
                                  RcRangeParameters(17, 21, -10),
                                  RcRangeParameters(17, 21, -12),
                                  RcRangeParameters(17, 21, -12),
                                  RcRangeParameters(19, 22, -12),
                                  RcRangeParameters(22, 23, -12)]),

        # 12BPP/16BPC
        RCRangeParametersFromCFG(341, 15, 2048, 19, 28, 27, 27,
                                 [RcRangeParameters(0, 6, 2),
                                  RcRangeParameters(6, 11, 0),
                                  RcRangeParameters(11, 15, 0),
                                  RcRangeParameters(14, 18, -2),
                                  RcRangeParameters(18, 21, -4),
                                  RcRangeParameters(19, 22, -6),
                                  RcRangeParameters(19, 23, -8),
                                  RcRangeParameters(19, 24, -8),
                                  RcRangeParameters(19, 24, -8),
                                  RcRangeParameters(19, 25, -10),
                                  RcRangeParameters(21, 25, -10),
                                  RcRangeParameters(21, 25, -12),
                                  RcRangeParameters(21, 25, -12),
                                  RcRangeParameters(23, 26, -12),
                                  RcRangeParameters(26, 27, -12)]),
    ],

    # 15BPP
    [
        # 15BPP/8BPC
        RCRangeParametersFromCFG(273, 15, 2048, 3, 12, 11, 11,
                                 [RcRangeParameters(0, 0, 10),
                                  RcRangeParameters(0, 1, 8),
                                  RcRangeParameters(0, 1, 6),
                                  RcRangeParameters(0, 2, 4),
                                  RcRangeParameters(1, 2, 2),
                                  RcRangeParameters(1, 3, 0),
                                  RcRangeParameters(1, 3, -2),
                                  RcRangeParameters(2, 4, -4),
                                  RcRangeParameters(2, 5, -6),
                                  RcRangeParameters(3, 5, -8),
                                  RcRangeParameters(4, 6, -10),
                                  RcRangeParameters(4, 7, -10),
                                  RcRangeParameters(5, 7, -12),
                                  RcRangeParameters(7, 8, -12),
                                  RcRangeParameters(8, 9, -12)]),

        # 15BPP/10BPC
        RCRangeParametersFromCFG(273, 15, 2048, 7, 16, 15, 15,
                                 [RcRangeParameters(0, 2, 10),
                                  RcRangeParameters(2, 5, 8),
                                  RcRangeParameters(3, 5, 6),
                                  RcRangeParameters(4, 6, 4),
                                  RcRangeParameters(5, 6, 2),
                                  RcRangeParameters(5, 7, 0),
                                  RcRangeParameters(5, 7, -2),
                                  RcRangeParameters(6, 8, -4),
                                  RcRangeParameters(6, 9, -6),
                                  RcRangeParameters(7, 9, -8),
                                  RcRangeParameters(8, 10, -10),
                                  RcRangeParameters(8, 11, -10),
                                  RcRangeParameters(9, 11, -12),
                                  RcRangeParameters(11, 12, -12),
                                  RcRangeParameters(12, 13, -12)]),

        # 15BPP/12BPC
        RCRangeParametersFromCFG(273, 15, 2048, 11, 20, 19, 19,
                                 [RcRangeParameters(0, 4, 10),
                                  RcRangeParameters(2, 7, 8),
                                  RcRangeParameters(4, 9, 6),
                                  RcRangeParameters(6, 11, 4),
                                  RcRangeParameters(9, 11, 2),
                                  RcRangeParameters(9, 11, 0),
                                  RcRangeParameters(9, 12, -2),
                                  RcRangeParameters(10, 12, -4),
                                  RcRangeParameters(11, 13, -6),
                                  RcRangeParameters(11, 13, -8),
                                  RcRangeParameters(12, 14, -10),
                                  RcRangeParameters(13, 15, -10),
                                  RcRangeParameters(13, 15, -12),
                                  RcRangeParameters(15, 16, -12),
                                  RcRangeParameters(16, 17, -12)]),

        # 15BPP/14BPC
        RCRangeParametersFromCFG(273, 15, 2048, 15, 24, 23, 23,
                                 [RcRangeParameters(0, 4, 10),
                                  RcRangeParameters(3, 8, 8),
                                  RcRangeParameters(6, 11, 6),
                                  RcRangeParameters(9, 14, 4),
                                  RcRangeParameters(13, 15, 2),
                                  RcRangeParameters(13, 15, 0),
                                  RcRangeParameters(13, 16, -2),
                                  RcRangeParameters(14, 16, -4),
                                  RcRangeParameters(15, 17, -6),
                                  RcRangeParameters(15, 17, -8),
                                  RcRangeParameters(16, 18, -10),
                                  RcRangeParameters(17, 19, -10),
                                  RcRangeParameters(17, 19, -12),
                                  RcRangeParameters(19, 20, -12),
                                  RcRangeParameters(20, 21, -12)]),

        # 15BPP/16BPC
        RCRangeParametersFromCFG(273, 15, 2048, 19, 28, 27, 27,
                                 [RcRangeParameters(0, 4, 10),
                                  RcRangeParameters(4, 9, 8),
                                  RcRangeParameters(8, 13, 6),
                                  RcRangeParameters(12, 17, 4),
                                  RcRangeParameters(17, 19, 2),
                                  RcRangeParameters(17, 20, 0),
                                  RcRangeParameters(17, 20, -2),
                                  RcRangeParameters(18, 20, -4),
                                  RcRangeParameters(19, 21, -6),
                                  RcRangeParameters(19, 21, -8),
                                  RcRangeParameters(20, 22, -10),
                                  RcRangeParameters(21, 23, -10),
                                  RcRangeParameters(21, 23, -12),
                                  RcRangeParameters(23, 24, -12),
                                  RcRangeParameters(24, 25, -12)])
    ]
]
